name: Android CI
# test
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3.2.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Build
        uses: actions/cache@v3.2.3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
            ~/.gradle/buildOutputCleanup/cache.properties
          key: gradle-builds-core-${{ github.sha }}
          restore-keys: |
            gradle-builds
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -storetype PKCS12 -keystore release.keystore -alias mykeyalias -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Example, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown" -storepass mypassword -keypass mypassword

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_alias: mykeyalias
          key_password: ${{ secrets.KEY_PASSWORD }}
        
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: snapshot
          path: |
            ${{ github.workspace }}/app/build/outputs/apk
#            ${{ github.workspace }}/app/build/outputs/mapping
